# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'doortwodoor' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for doortwodoor
  
  # React Native Firebase required pods
  pod 'Firebase/Core'
  
  # React Native Firebase optional pods
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
end
